extends: airbnb-base
parser: babel-eslint
env:
  browser: true
  es6: true
rules:
  arrow-parens: off
  comma-dangle:
    - error
    - never
  curly:
    - error
    - multi-or-nest
    - consistent
  global-require: off
  function-paren-newline: off
  max-len: off
  no-param-reassign: off
  no-console: off
  no-mixed-operators: off
  no-multi-assign: off
  no-nested-ternary: off
  no-plusplus: off
  no-return-assign: off
  no-underscore-dangle: off
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-use-before-define: off
  prefer-destructuring:
  - error
  - VariableDeclarator:
      array: false
      object: true
    AssignmentExpression:
      array: false
      object: false
  - enforceForRenamedProperties: false
  import/no-dynamic-require: off
  import/no-extraneous-dependencies: off
